### ISSUE TITLE
Motion-Sensor-GUI.py: Eyesjun instance has no attribute 'srfechotime'

### ISSUE THREAD

**Issue by ofenerci** [wavicles/Plugins-for-ExpEYES#5]
Dear Praveen,

When I run Motion-Sensor-GUI.py, I get an error:
------------------------------------------->---------------------------------------
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1539, in __call__
    return self.func(*args)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 590, in callit
    func(*args)
  File "motion-sensor.py", line 73, in update
    tt = p.srfechotime(9,0)
AttributeError: Eyesjun instance has no attribute 'srfechotime'
----------------------------------------<-------------------------------------------

I have no idea how to fix it. 

Best Regards,
Ozhan

**Comment by wavicles** [comment]
Hi Ozhan 
Please check the firmware version you are using, it should be 1.1
The function call  p.srfechotime  was not there in 1.0. 
The information about firmware is displayed on the top of the ExpEYES-Jr GUI

Try this simple code
import expeyes.eyesj
p=expeyes.eyesj.open()

p.set_state(10,1)             # set OD1 high
tt = p.srfechotime(9,0)   # connect Trig to SQR2 and Echo to SEN

Hope it works.

Best Regards
Praveen

**Comment by ofenerci** [comment]
The debian repository of Expeyes was missing "srfechotime". It was corrected by Georges Khaznadar in debian repository. Now it works.
